title: Dynamix Play Therapy - Play Therapy in East Dorset
email: rosie@dynamixplaytherapy.co.uk
description: A play therapy company based in East Dorset
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dynamixplaytherapy.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
